AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.9
    Timeout: 30
    Environment:
      Variables:
        DB_HOST: wp-rds-database.cxhyds0avgup.ap-northeast-1.rds.amazonaws.com
        DB_NAME: todo_db
        DB_USER: todo_admin
        DB_PASSWORD: todotodo1117
    VpcConfig:
      SubnetIds:
        - subnet-0e9a247f0c49c5fb0
        - subnet-088db5ae049bb9e92
      SecurityGroupIds:
        - sg-0cee7972dcb7f1b32


Resources:
  GetTodosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: get_todos.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        GetTodosApi:
          Type: Api
          Properties:
            Path: /todos
            Method: GET
            RestApiId: !Ref TodoApi

  AddTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: add_todo.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        AddTodoApi:
          Type: Api
          Properties:
            Path: /todos
            Method: POST
            RestApiId: !Ref TodoApi

  UpdateTodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: update_todo.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        UpdateTodoApi:
          Type: Api
          Properties:
            Path: /todos
            Method: PUT
            RestApiId: !Ref TodoApi

  TodoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: TodoApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

Outputs:
  GetTodosApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Get Todos function"
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos"
  AddTodoApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Add Todo function"
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos"
  UpdateTodoApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Update Todo function"
    Value: !Sub "https://${TodoApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todos"
